#Building dockerImage for consumer using python latest file
FROM python:latest
# RUN mkdir /consumer
WORKDIR /consumer

# COPY ./requirements.txt .
COPY . /requirements.txt
COPY . .

#Installing required libraries specified in requirements.txt file
RUN pip install -r requirements.txt 

#Execute consumer.py file in python mode
CMD ["python", "consumer.py"]