version: '3'
services:
#Docker service for SCMXpert application
  app:
    image: nareshkumar1234/scmlite:v3
    ports:
      - 8000:8000
    volumes:
      - ./app:/app
#Docker service for kafka-zookeeper
  zookeeper:
    image: bitnami/zookeeper:latest
    ports:
      - 2181:2181
    volumes:
      - zookeeper_data:/bitnami
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes

#Docker service for kafka
  kafka:
    image: bitnami/kafka:latest   
    ports:
      - 9092:9092
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper:2181
      - ALLOW_PLAINTEXT_LISTENER=yes      
      - KAFKA_HEAP_OPTS=-Xmx200M 
    depends_on:
      - zookeeper
    healthcheck:
      test: ["CMD-SHELL", "kafka-topics.sh --bootstrap-server 127.0.0.1:9092 --list"]
      interval: 30s
      timeout: 15s
      retries: 3
    volumes:
      - kafka_data:/bitnami

#Docker service for kafka-server
  server:
    image: nareshkumar1234/socket:latest
    ports:
      - 12345:12345
    volumes:
      - ./server:/server

#Docker service for kafka-producer
  producer:
    image: nareshkumar1234/producer:latest
    depends_on:
      kafka:
        condition: service_healthy
    volumes:
    - ./producer:/producer

#Docker service for kafka-consumer
  consumer:
    image: nareshkumar1234/consumer:latest

    depends_on:
      kafka:
        condition: service_healthy

    volumes:
    - ./consumer:/consumer


volumes:
  app:
    driver: local
  server:
    driver: local
  producer:
    driver: local
  consumer:
    driver: local
  zookeeper_data:
    driver: local
  kafka_data:
    driver: local